#!/bin/bash

rm $3.txt

echo
echo "START"

i="1"
M="$[$2+1]"

while [ $i -lt $M ]
do
  echo "Downloading Chapter $i..."
  wget -A "*.html" -p -q -nd $1/$i.html
  cat ./$i.html | grep "<br>" > $i.txt
  sed -i 's/<br>/\
  /g' $i.txt
  sed -i 's/<[^<]*>//g' $i.txt
  sed -i 's/\&nbsp;//g' $i.txt
  sed -i 's/^[[:space:]]*//g' $i.txt
  cat $i.txt >> $3.txt
  rm $i.txt
  rm $i.html
  i=$[$i+1]
done;

echo "END"