#!/bin/bash
echo
echo "START"

rm $2.txt
wget -r -l 1 -A "*.html" -p -q -nd $1
rm index.html
rm weeksortbook.html

sed -i 's/<br>/\
/g' *.html
cat *.html >> $2.txt
rm *.html

sed -i 's/\&nbsp;//g' $2.txt
sed -i 's/<[^<]*>//g' $2.txt

echo "END"