#!/bin/bash

rm $3.txt

echo
echo "START"

i="1"
M="$[$2+1]"

while [ $i -lt $M ]
do
  echo "Downloading Chapter $i..."
  wget -p -q -nd $1/$i.shtml
  cat ./$i.shtml | grep "<p>" > $i.txt
  sed -i 's/<p>//g' $i.txt
  sed -i 's/<\/p>/\
  /g' $i.txt
  sed -i 's/<[^<]*>//g' $i.txt
  sed -i '/[:space:][^C]*/d' $i.txt
  sed -i 's/^[[:space:]]*//g' $i.txt
  cat $i.txt >> $3.txt
  rm $i.txt
  rm $i.shtml
  i=$[$i+1]
done;

echo "END"
